### numpy用法详解

In [1]:
# 安装numpy

# 使用pip安装numpy(通用、快捷)
!pip3 install numpy

# linux使用包管理器安装numpy
# Ubuntu/Debian使用
# sudo apt-get install python3-numpy
# centos/redhat使用
# sudo yum install python3-numpy

Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple


In [3]:
# 验证numpy是否安装成功
import numpy as np
print(np.eye(3))  # 输出3*3的单位的对角矩阵

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### array函数的参数介绍
---
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
- object: 可以是任何可迭代对象，比如list、tuple、range等
- dtype: 指定数组的数据类型，默认为None，表示自动推断
- copy: 指定是否复制数据，默认为True
- order: 指定数组的存储顺序，默认为None，表示自动推断
- subok: 指定是否允许访问子数组，默认为False
- ndmin: 指定数组的最小维度，默认为0

In [9]:
a = np.array([1, 2, 3]) # 创建一个一维数组
b = np.array([[1, 2], [3, 4]]) # 创建一个2*2的数组
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


##### numpy的数据类型
> numpy的数据类型也是array函数的参数dtype的类型.
---
- bool_ :bool类型
- int_ :默认的整数类型
- intc :与c的int类型一样,一般是int32或int64
- intp :用于索引的整数类型，一般是int32或int64
- int8 :字节(-128~127)
- int16 :整数(-32768~32767)
- int32 :整数(-2147483648~2147483647)
- int64 :整数(-9223372036854775808~9223372036854775807)
- uint8 :无符号整数(0~255)
- uint16 :无符号整数(0~65535)
- uint32 :无符号整数(0~4294967295)
- uint64 :无符号整数(0~18446744073709551615)
- float_ :float64类型的简写
- float16 :半精度浮点数
- float32 :单精度浮点数
- float64 :双精度浮点数
- complex_ :complex128类型的简写
- complex64 :单精度复数
- complex128 :双精度复数

##### 数据类型对象dtype
---
> 字节顺序是通过对数据类型预先设定<或>来指定的,<最小值存储在最小地址,>重要字节存储在最小地址
numpy.dtype(object,align=False,copy=False)
- object: 要转换为的数据类型对象
- align: 如果为True,填充字段类似c的结构体
- copy: 复制dtype对象,如果为False,则对内置数据类型对象的引用

In [25]:
# 数据类型可以使用相应的字符串来代替,int8,int16,int32,int64可分别用字符串'i1','i2','i4','i8'表示,i后面的数字乘以8,对应的就是字节数
print(np.dtype('i8')) # 输出int64
print(np.dtype('u8')) # 输出uint64
print(np.dtype('f8')) # 输出float64
print(np.dtype('c8')) # 输出complex64


int64
uint64
float64
complex64


In [34]:
# 创建结构化数据类型
dt = np.dtype([('age', np.int8), ('name','S10')]) 

# 将数据类型应用于数组对象
a = np.array([(10, b'Guido'), (20, b'Steve')], dtype=dt) 

print(a)

[(10, b'Guido') (20, b'Steve')]


##### 内建类型都有一个唯一定义它的字符代码
- 字符b 对应的是bool_
- 字符i 对应的是int_整数型
- 字符u 对应的是uint_无符号整数型
- 字符f 对应的是float_浮点型
- 字符c 对应的是complex_复数浮点型
- 字符O 对应的是object_对象
- 字符S,a 对应的是bytes_字符串
- 字符U 对应的是unicode_字符串
- 字符V 对应的是void_空类型
- 字符M 对应的是datetime64[D]_日期时间型
- 字符m 对应的是timedelta64[D]_时间型
